import "./globals.css";

export const metadata = {
  title: "밍뇽이랑 밍수",
  description: "Generated by 밍수",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
